/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.scanner.jsonc --env-file=/dev/null --include-runtime=false --env-interface=ScannerEnvBindings scanner-configuration.d.ts` (hash: 055c81c9bdf6d61307ce4a75d6f58949)
interface __BaseEnv_ScannerEnvBindings {
  PREVIEWS: R2Bucket;
  SCAN_RESULTS: Queue;
  BROWSER: BrowserRun;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./scanner/index");
  }
  interface Env extends __BaseEnv_ScannerEnvBindings {}
}
interface ScannerEnvBindings extends __BaseEnv_ScannerEnvBindings {}
